DROP TABLE IF EXISTS PERSONAS;  

CREATE TABLE PERSONAS (  
	ID INT PRIMARY KEY,  
	NOMBRE VARCHAR(50) NOT NULL,  
	APELLIDO VARCHAR(50) NOT NULL,
	RFC VARCHAR(50) NOT NULL,
	CURP VARCHAR(50) NOT NULL,
	EDAD INT,
	SEXO VARCHAR(50) NOT NULL,
	NACIONALIDAD VARCHAR(50) NOT NULL  
);